name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:

  duster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: phpstan

      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --no-interaction
          npm ci
          npm run build

      - name: "Duster Lint"
        uses: tighten/duster-action@v3
        with:
          args: lint
      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint
